---
# tasks file for webservers
  - name: Ensure group deploy exists
    group:
       name: deloitte
       state: present

  - name: Ensure user deploy-user exists
    user:
       name: deploy-user
       state: present

#  - name: install packages
#    yum:
#       name: "{{item}}"
#       state: present
#    with_items:
#       - git
#       - ntp
#       - vim

  - name: Ansible variables
    debug:
       msg: "{{myname}}"